//
// auto-generated by op2.m on 30-May-2011 22:03:11
//

// header

#include <utility>
#define __NO_STD_VECTOR //use cl::vector
#include <CL/cl.h>

#include "op_lib.cl.cpp"

// global constants

#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif


extern cl_mem g_const_d;
 

void op_decl_const_char(int dim, char const *type,
            int size, char *dat, char const *name){
  //cutilSafeCall(cudaMemcpyToSymbol(name, dat, dim*size));
}

// user kernel files

//#include "res_calc.h"

#include "save_soln_kernel.cl.cpp"
#include "adt_calc_kernel.cl.cpp"
#include "res_calc_kernel.cl.cpp"
#include "bres_calc_kernel.cl.cpp"
#include "update_kernel.cl.cpp"

